### ISSUE TITLE
No build triggered

### ISSUE THREAD

**Issue by th-otto** [freemint/gemma#4] opened 2018-07-18 14:15 UTC
Pushing to this repo does not seem to trigger automated builds currently

**Comment by mikrosk** [comment] 2018-07-18 14:17
Not only for this repository but for all of them. I have no idea what has happened.

**Comment by th-otto** [comment] 2018-07-18 14:21
The last build is from your commit updating the README.md, which was already after the move. Same in the other 2 repos.

**Comment by th-otto** [comment] 2018-07-18 14:26
There had been some service inavailabilities of github.com in the last few day, maybe travis went mad?

**Comment by mfro0** [comment] 2018-07-18 19:23
just done a freemint (and libcmini) commit and both built fine.

So it's probably not a general problem.

**Comment by th-otto** [comment] 2018-07-18 19:31
Yes, but gemlib and mintlib also seem to be affected. More specifically, no build has been triggered in these repos after their .travis.yml file has been updated. Could there be something wrong with their syntax after the update?

**Comment by mfro0** [comment] 2018-07-18 19:45
yes, there appears to be something wrong with .travis.yml. See here: https://travis-ci.org/freemint/gemma/requests?requestId=124333710

You can trigger a build on the "More options" pulldown on the top right, btw.

**Comment by mikrosk** [comment] 2018-07-18 20:41
Why Travis didn't complain immediately about bad .travis.yml is beyond me (usually I get an ERRORED email). I'll take a look.

**Comment by th-otto** [comment] 2018-07-18 20:49
Because the build did not fail... it wasn't started at all ;)

**Comment by mikrosk** [comment] 2018-07-18 20:52
I've found the cause... but even if the build doesn't start, I was always getting an ERRORED emails. Really odd.

**Comment by mikrosk** [comment] 2018-07-18 21:05
OK, fixed in all repositories. Reason for this change (and fail) was that I had discovered a funny bug: if you happened to be a person with write access to freemint repositories and you forked a repository and made own branch and pushed it without change, it would get published in the freemint.github.io repository. :)

Not a disaster but I was quite surprised to find some of my branches there. (now deleted)

**Closed as completed by mikrosk** 2018-07-18 21:05 UTC
